# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.pty = true

  # vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
  config.vm.box = "dummy"

  config.vm.define :jenkins_slack do |t|
  end

  config.vm.provider :aws do |aws, override|
  
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']			# you can hard code your access key and secret...
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']	# ... but it's not a great idea
    
    aws.keypair_name = "awsroot" 							# <-- change to your ec2 key pair name...
    override.ssh.private_key_path = "../awsroot.pem" 		# ...and then put your key in this file
    
    aws.security_groups = ["my-security-group"] 			# <-- change to your ec2 security group name
     
    aws.region = "eu-west-1"								# AWS region Ireland
    aws.ami = "ami-a10897d6" 								# this AMI is for eu-west-1 (Ireland)
    
    aws.instance_type = "t2.small"
    aws.block_device_mapping = [{ 'DeviceName' => '/dev/xvda', 'Ebs.VolumeSize' => 20 }]
    aws.user_data = File.read("user_data.aws")

    aws.tags = {
      'Name' => "jenkins_slack",
      'ctrl' => "vagrant"
    }
    
    override.ssh.username = "ec2-user"
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/inventory/ec2.py"
    ansible.verbose = "vvvv"
    ansible.sudo = true
    ansible.limit = "all"
  end

end
